### ISSUE TITLE
Will the vNext be released soon? 

### ISSUE THREAD

**Issue by carlshe** [twlikol/GridViewScroll#10]
I found the exciting demo picture of vNext on the web page. It looks the footer row has been already added.
Will the new version be released soon? I can't wait to its release!

Thanks in advance!

**Comment by carlshe** [comment]
Is it possible to divide table into parts at server side?

**Comment by twlikol** [comment]
Sorry I do not quite understand what you mean.

**Comment by carlshe** [comment]
Modify rendering process of gridview control so it can be presented as multi-tables, and of course it is still under control of javascript library at client side.
