### ISSUE TITLE
set fixed width for td not working

### ISSUE THREAD

**Issue by sumit3285** [twlikol/GridViewScroll#11]
i tried example from here http://gridviewscroll.aspcity.idv.tw/, with plain html javascript, however i am unable to set fixed width for table cells (td)
really wonderful library it would be great if we can apply fixed width for td. thanks

**Comment by twlikol** [comment]
Do you try this sample?

http://gridviewscroll.aspcity.idv.tw/Demo.aspx#CellWrap

**Comment by sumit3285** [comment]
Yes, I tried it and unfortunately it didn't worked, i want to make every td starting from 4th position (you can exclude the 4th and show me how to make each td fixed width)

**Comment by sumit3285** [comment]
finally managed to set width using table-layout property of table set to fixed. Thanks
