### ISSUE TITLE
The issue of TH rowspan and colspan

### ISSUE THREAD

**Issue by fusfus** [twlikol/GridViewScroll#25]
Hi ,
Thanks for this plugin, it's very powerful.
But I find one issue need your help.
The below html of table can not apply GridViewScroll.
It will caused <b>gridCopyBody[0].rows[j].cells[cellIndex].childNodes[0].style.width = width + "px"; </b> error.
Could you kindly help to check this issue ?

<span>
        $('#Table1').gridviewScroll({
            width: 1660,
            height: 300,
            freezesize: 1,
            headerrowcount: 3
        });
</span>

<table cellspacing="0" id="Table1" style="width:100%;border-collapse:collapse;"> 
    <tr class="GridviewScrollHeader"> 
        <th rowspan="3" scope="col">ProductID</th> 
        <td colspan="7">Product Full Information</td> 
        <th rowspan="2" colspan="7" scope="col">New</th> 
    </tr> 
    <tr class="GridviewScrollHeader"> 
        <td colspan="4">Basic</td> 
        <td colspan="3">Addition</td> 
    </tr> 
    <tr class="GridviewScrollHeader"> 
        <th scope="col">Name</th> 
        <th scope="col">Number</th> 
        <th scope="col">SafetyStockLevel</th> 
        <th scope="col">ReorderPoint</th> 
        <th scope="col">StandardCost</th> 
        <th scope="col">ListPrice</th> 
        <th scope="col">Weight</th> 
        <th scope="col">Size</th> 
        <th scope="col">SellStartDate</th> 
    </tr> 
    <tr class="GridviewScrollItem"> 
        <td style="background-color: #EFEFEF;">747</td> 
        <td>HL Mountain Frame - Black, 38</td> 
        <td>FR-M94B-38</td> 
        <td>500</td> 
        <td>375</td> 
        <td>739.0410</td> 
        <td>1349.6000</td> 
        <td>2.68</td> 
        <td>38</td> 
        <td>7/1/2005 12:00:00 AM</td> 
    </tr>    
</table>

**Comment by twlikol** [comment]
Header row freeze In some complex case is not working.
This is a known bug.
