### ISSUE TITLE
How do we maintain vertical scroll postion of GridViewScroll after postback?

### ISSUE THREAD

**Issue by tuien** [twlikol/GridViewScroll#29]

**Comment by gymclasshero** [comment]
Had the same problem, found the answer here:
http://gridviewscroll.aspcity.idv.tw/Demo/Advanced.aspx#MaintainScrollPosition

Hope this helps!

**Comment by tuien** [comment]
Thank you, I'll try


Have a nice day (-: Tuien Nguien


________________________________

**Comment by tuien** [comment]
It worked perfect!

Thank you so much
