### ISSUE TITLE
How to reposition the scrollbar to a specific row?

### ISSUE THREAD

**Issue by godchum** [twlikol/GridViewScroll#34]
Hi,

Can you help me how to reposition the scrollbar into a specific row that I want to focus on?
By the way thanks for this tool. This helps me a lot on freezing columns.

Thanks for your help.

Dorothy

**Comment by twlikol** [comment]
Try add the following code to gridviewScroll function inside

this.moveToRowIndex = function (rowIndex) {
    moveTo(rowIndex);
};

Then you can call this method like:

gridView1 = $('#GridView1').gridviewScroll({
});
gridView1.moveToRowIndex(20);

**Comment by godchum** [comment]
Hi Likol Lee,

Thanks for the reply. But it's not working for me. 

I tried adding the same function inside gridviewScroll.min.js
(function (n) {
    jQuery.fn.extend({
        gridviewScroll: function (t) {
            this.moveToRowIndex = function (rowIndex) {
                moveTo(rowIndex);
            };
.
.
.
 }), jQuery.fn.extend({ gridviewScroll: jQuery.fn.gridviewScroll })
})(jQuery)

and in my page I added this:
 $(".img").click(function () {
                var rowIdx = $(this).prop("RowIndex");
                 gridviewScroll();
                gridView1 = $('#mainGrid').gridviewScroll({
                });
                gridView1.moveToRowIndex(rowIdx);
                //$(this).scrollIntoView();

            });
but it's not working. I have an image column in my gridview/repeater control and when this image is clicked I am collapsing the child rows. What I want to do is when I click the image on that row, the Scrollbar should default that Scrolltop position on that rowIndex.

Regards,
Dorothy
