### ISSUE TITLE
Column width not adjusted automatically.

### ISSUE THREAD

**Issue by Ganeshtpt** [twlikol/GridViewScroll#36]
Hi,
I am using gridviewscroll past few days. In that i have used more columns (more than 15 columns in some of the grid). But, the alignment of the column is Zig-Zag. it means the columns alignment is merging with others. i tiried many ways. but it is not working. This is urgent.pls. help.
![screenshot](https://cloud.githubusercontent.com/assets/25198034/23944216/09b5096c-0998-11e7-8d31-6880f3943011.png)

**Comment by twlikol** [comment]
Most of the reasons for column not being aligned are cause by style.

You can try to adjust from the CSS (like padding).

**Comment by Ganeshtpt** [comment]
can you pls. give me the example...

**Comment by twlikol** [comment]
You can refer to the example below
http://gridviewscroll.aspcity.idv.tw/Demo.aspx

**Comment by Ganeshtpt** [comment]
Thanks..

But,i need where we want to change the column width size in the CSS....

pls..
