### ISSUE TITLE
getting error if row count = 0

### ISSUE THREAD

**Issue by burhanfarooqws** [twlikol/GridViewScroll#47]
Hi,

getting error if row count = 0.

gridviewscroll.js:34 Uncaught TypeError: Cannot read property 'rows' of null
    at GridViewScroll.enhance (gridviewscroll.js:34)

![image](https://user-images.githubusercontent.com/17730402/32574368-d58c4cc4-c4f2-11e7-9609-d58013b7d122.png)

**Comment by burhanfarooqws** [comment]
Hi,

for time being I applied these checks:

```
if (this.ContentGrid == null) return;
if (this.ContentGrid.rows.length == 0) return;
```

Actually `this.ContentGrid` is null when zero rows.

Thanks

**Comment by twlikol** [comment]
I had commit an update, It is because the element does not exist.
