### ISSUE TITLE
Alignment Issue with header and row columns

### ISSUE THREAD

**Issue by sunilbsharma** [twlikol/GridViewScroll#49]
I have grid view which has dynamic columns, When number of columns to be shown in gridview are less, the header and rows are not aligned. Header width is lower than the datarow width.

I have kept grid view in panel with width set as document width and gridview width is "100%"
The other issues is when i keep the freezcolumn as true. Then also there is alignment issue with Header Row and DataRow.
Can you please help me on this?
Thanks!

**Comment by twlikol** [comment]
Can you provide an example to reproduce the problem?
You can send mail to twlikol@msn.com

**Comment by acasals** [comment]
I got the same issue. Headers and columns got misaligned when no scroll is needed, I mean, when the table fits in window.
You can reproduce the problem if you change parent div style to width:100% and in options set options.width="100%" and options.height="100%" in your ParentSize.html example.
I attach the modified ParentSize.html for clarity.

[ParentSize.html.txt](https://github.com/twlikol/GridViewScroll/files/2113218/ParentSize.html.txt)


Anyway, GridViewScroll is great!
